### ISSUE TITLE
Vercel alternatives (like Railway)

### ISSUE THREAD

**Issue by Rowan-Paul** [Patrickroelofs/tracktr#33]
#### Requirements 

- Database hosting 
- Hosting all applications in monorepo
- Team usage
- Preview environments

#### Services 

- https://railway.app/pricing
- https://fly.io/plans
- Supabase (database only)

**Comment by Patrickroelofs** [comment]
we can create a postgres database at vercel, price seems to be free for now, i think paying for a database is almost unavoidable sadly

**Comment by Patrickroelofs** [comment]
AWS all the way

**Comment by Patrickroelofs** [comment]
Vercel pro 😎
